; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = ESP32-Hardware
description = Librairy for esp32
; Leave default_envs empty so it will build all env
default_envs = 
; build_dir = ${PROJECT_DIR}/.pio/build

[env]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform = espressif32
board = ESP32-S3-Tiny
framework = arduino
upload_protocol = esptool
build_type = debug
build_src_filter = 
	+<*>
	+<../${PIOENV}/${PIOENV}.cpp>
upload_speed = 921600
monitor_speed = 921600
monitor_filters = 
	colorize
	time
	send_on_enter
	esp32_exception_decoder
monitor_echo = yes
monitor_eol = LF
lib_deps = 
	ESP32_Helper=symlink://../ESP32_Helper
	robotis-git/Dynamixel2Arduino@^0.8.0
	;adafruit/Adafruit SSD1306@^2.5.16
	greiman/SSD1306Ascii@^1.3.5
	adafruit/Adafruit INA219@^1.2.3
	fastled/FastLED@3.9.16
	stm32duino/STM32duino VL53L8CX @ ^2.0.3

[env:main]
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=c++17
	-std=gnu++17
	-D ARDUINO_ESP32S3_DEV
;	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-D NO_WIFI
	-D SIMULATOR
	-D WOKWI
	-D ESP32_HARDWARE_LIB
